#!/bin/bash
# SPDX-License-Identifier: 0BSD
set -euo pipefail
task_root="$(cd -- "$(/usr/bin/dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
exec /usr/bin/python3 -E -s -B "$task_root/src/controller.py" "$@"
